import type { MeditationDetail, MeditationListItem } from '@contracts/meditation.contract';

// FEAT-3: Meditation mock data

export const mockMeditation: MeditationDetail = {
  id: 'meditation-1',
  userId: 'user-1',
  analysisId: 'analysis-1',
  content: '요한복음 3:16의 핵심 메시지는 하나님의 무조건적인 사랑입니다...',
  isAutoGenerated: true,
  status: 'draft',
  createdAt: '2026-01-15T09:00:00.000Z',
  updatedAt: '2026-01-15T09:00:00.000Z',
};

export const mockMeditationList: MeditationListItem[] = [
  {
    id: 'meditation-1',
    analysisId: 'analysis-1',
    content: '요한복음 3:16의 핵심 메시지는...',
    isAutoGenerated: true,
    status: 'draft',
    createdAt: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 'meditation-2',
    analysisId: null,
    content: '오늘 말씀을 통해 느낀 점...',
    isAutoGenerated: false,
    status: 'published',
    createdAt: '2026-01-14T09:00:00.000Z',
  },
];
