'use client';

import { useEffect, useState, use } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/stores/authStore';
import { useMeditationStore } from '@/stores/meditationStore';
import {
  getMeditation,
  updateMeditation,
  deleteMeditation,
  generateMeditation,
} from '@/services/meditationService';
import MeditationEditor from '@/components/meditation/MeditationEditor';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';

// FEAT-3: Meditation detail page

interface MeditationDetailPageProps {
  params: Promise<{ id: string }>;
}

const statusLabels: Record<string, { label: string; className: string }> = {
  draft: { label: '초안', className: 'bg-yellow-100 text-yellow-700' },
  published: { label: '게시됨', className: 'bg-green-100 text-green-700' },
};

export default function MeditationDetailPage({ params }: MeditationDetailPageProps) {
  const { id } = use(params);
  const router = useRouter();
  const accessToken = useAuthStore((s) => s.accessToken);
  const { currentMeditation, isLoading, error, setCurrentMeditation, setLoading, setError } =
    useMeditationStore();

  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  useEffect(() => {
    if (!accessToken) return;

    setLoading(true);
    getMeditation(accessToken, id)
      .then((data) => {
        setCurrentMeditation(data);
      })
      .catch((err: Error) => {
        setError(err.message);
      })
      .finally(() => {
        setLoading(false);
      });

    return () => {
      setCurrentMeditation(null);
    };
  }, [accessToken, id, setCurrentMeditation, setLoading, setError]);

  if (!accessToken) {
    return (
      <div className="flex items-center justify-center py-xl">
        <p className="text-text-secondary">로그인이 필요합니다</p>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-xl">
        <span
          className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent"
          role="status"
          aria-label="loading"
        />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center py-xl">
        <p className="text-red-500">{error}</p>
      </div>
    );
  }

  if (!currentMeditation) {
    return (
      <div className="flex items-center justify-center py-xl">
        <p className="text-text-secondary">묵상을 찾을 수 없습니다</p>
      </div>
    );
  }

  const handleSave = async (content: string) => {
    setIsSaving(true);
    const updated = await updateMeditation(accessToken, id, content);
    setCurrentMeditation(updated);
    setIsEditing(false);
    setIsSaving(false);
  };

  const handleDelete = async () => {
    await deleteMeditation(accessToken, id);
    router.push('/meditation');
  };

  const handleGenerate = async (analysisId: string): Promise<string> => {
    const result = await generateMeditation(accessToken, analysisId);
    return result.content;
  };

  const statusInfo = statusLabels[currentMeditation.status] ?? {
    label: currentMeditation.status,
    className: 'bg-gray-100 text-gray-700',
  };

  if (isEditing) {
    return (
      <div className="flex flex-col gap-lg py-lg">
        <h1 className="text-2xl font-bold text-text-primary">묵상 수정</h1>
        <MeditationEditor
          initialContent={currentMeditation.content}
          analysisId={currentMeditation.analysisId ?? undefined}
          meditationId={currentMeditation.id}
          isAutoGenerated={currentMeditation.isAutoGenerated}
          onSave={handleSave}
          onCancel={() => setIsEditing(false)}
          onGenerate={currentMeditation.analysisId ? handleGenerate : undefined}
          isSaving={isSaving}
        />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-lg py-lg">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-text-primary">묵상 노트</h1>
        <div className="flex items-center gap-sm">
          <Button variant="secondary" onClick={() => setIsEditing(true)}>
            수정
          </Button>
          <Button variant="ghost" onClick={() => setShowDeleteConfirm(true)}>
            삭제
          </Button>
        </div>
      </div>

      <Card className="flex flex-col gap-md">
        <div className="flex items-center gap-sm">
          {currentMeditation.isAutoGenerated && (
            <span className="rounded-md bg-accent-light px-sm py-xs text-xs font-medium text-accent">
              AI 생성
            </span>
          )}
          <span
            className={['rounded-md px-sm py-xs text-xs font-medium', statusInfo.className].join(
              ' ',
            )}
          >
            {statusInfo.label}
          </span>
          <span className="text-xs text-text-secondary">
            {new Date(currentMeditation.createdAt).toLocaleDateString('ko-KR')}
          </span>
        </div>

        <p className="whitespace-pre-wrap font-serif text-text-primary leading-relaxed">
          {currentMeditation.content}
        </p>

        {currentMeditation.updatedAt !== currentMeditation.createdAt && (
          <p className="text-xs text-text-secondary">
            수정됨: {new Date(currentMeditation.updatedAt).toLocaleDateString('ko-KR')}
          </p>
        )}
      </Card>

      {showDeleteConfirm && (
        <Card className="border-red-200 bg-red-50">
          <div className="flex flex-col gap-md">
            <p className="text-sm text-red-700">
              이 묵상을 삭제하시겠습니까? 삭제 후 복구할 수 없습니다.
            </p>
            <div className="flex items-center gap-sm">
              <Button variant="ghost" onClick={() => setShowDeleteConfirm(false)}>
                취소
              </Button>
              <button
                onClick={handleDelete}
                className="rounded-md bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700"
              >
                삭제 확인
              </button>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
}
