import { SignJWT } from 'jose';

// FEAT-0: Test helper utilities

const JWT_SECRET = new TextEncoder().encode('test-jwt-secret-for-testing');
const JWT_REFRESH_SECRET = new TextEncoder().encode('test-refresh-secret-for-testing');

export function createTestUser(overrides?: Partial<TestUser>): TestUser {
  return {
    id: 'test-user-id-1',
    email: 'test@beesvat.com',
    passwordHash: '$2a$12$mockhashedpassword',
    nickname: '테스트 사용자',
    profileImage: null,
    role: 'user',
    createdAt: new Date('2026-01-01T00:00:00Z'),
    updatedAt: new Date('2026-01-01T00:00:00Z'),
    deletedAt: null,
    ...overrides,
  };
}

export async function createTestAccessToken(userId: string): Promise<string> {
  return new SignJWT({ sub: userId, type: 'access' })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt()
    .setExpirationTime('15m')
    .sign(JWT_SECRET);
}

export async function createTestRefreshToken(userId: string): Promise<string> {
  return new SignJWT({ sub: userId, type: 'refresh' })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt()
    .setExpirationTime('7d')
    .sign(JWT_REFRESH_SECRET);
}

export function createTestAnalysis(overrides?: Partial<TestAnalysis>): TestAnalysis {
  return {
    id: 'test-analysis-id-1',
    userId: 'test-user-id-1',
    book: '요한복음',
    chapter: 3,
    verseStart: 16,
    verseEnd: 16,
    passageText: '하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니',
    status: 'completed',
    rating: null,
    createdAt: new Date('2026-01-01T00:00:00Z'),
    updatedAt: new Date('2026-01-01T00:00:00Z'),
    ...overrides,
  };
}

export function createTestMeditation(overrides?: Partial<TestMeditation>): TestMeditation {
  return {
    id: 'test-meditation-id-1',
    userId: 'test-user-id-1',
    analysisId: 'test-analysis-id-1',
    content:
      '하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 이는 저를 믿는 자마다 멸망하지 않고 영생을 얻게 하려 하심이라. 이 구절은 하나님의 무한한 사랑을 보여줍니다.',
    isAutoGenerated: false,
    status: 'published',
    createdAt: new Date('2026-01-01T00:00:00Z'),
    updatedAt: new Date('2026-01-01T00:00:00Z'),
    ...overrides,
  };
}

// Type definitions for test data
interface TestUser {
  id: string;
  email: string;
  passwordHash: string | null;
  nickname: string;
  profileImage: string | null;
  role: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
}

interface TestAnalysis {
  id: string;
  userId: string;
  book: string;
  chapter: number;
  verseStart: number;
  verseEnd: number;
  passageText: string;
  status: string;
  rating: number | null;
  createdAt: Date;
  updatedAt: Date;
}

interface TestMeditation {
  id: string;
  userId: string;
  analysisId: string | null;
  content: string;
  isAutoGenerated: boolean;
  status: string;
  createdAt: Date;
  updatedAt: Date;
}
