import { z } from 'zod';

// FEAT-3: Meditation Note API Contract

// === Request Schemas ===
export const createMeditationRequestSchema = z.object({
  analysisId: z.string().uuid().optional(),
  content: z.string().min(1, '묵상 내용을 입력해주세요'),
});

export const updateMeditationRequestSchema = z.object({
  content: z.string().min(1, '묵상 내용을 입력해주세요'),
});

export const generateMeditationRequestSchema = z.object({
  analysisId: z.string().uuid('유효한 분석 ID를 입력해주세요'),
});

export const meditationQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(50).default(10),
});

// === Response Types ===
export interface MeditationDetail {
  id: string;
  userId: string;
  analysisId: string | null;
  content: string;
  isAutoGenerated: boolean;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface MeditationListItem {
  id: string;
  analysisId: string | null;
  content: string; // truncated preview
  isAutoGenerated: boolean;
  status: string;
  createdAt: string;
}

export interface GenerateMeditationResponse {
  id: string;
  content: string;
  isAutoGenerated: boolean;
}

// === Inferred Types ===
export type CreateMeditationRequest = z.infer<typeof createMeditationRequestSchema>;
export type UpdateMeditationRequest = z.infer<typeof updateMeditationRequestSchema>;
export type GenerateMeditationRequest = z.infer<typeof generateMeditationRequestSchema>;
export type MeditationQuery = z.infer<typeof meditationQuerySchema>;
