'use client';

import Link from 'next/link';
import type { MeditationListItem } from '@contracts/meditation.contract';
import Card from '@/components/ui/Card';

// FEAT-3: Meditation card component

interface MeditationCardProps {
  meditation: MeditationListItem;
}

const statusLabels: Record<string, { label: string; className: string }> = {
  draft: { label: '초안', className: 'bg-yellow-100 text-yellow-700' },
  published: { label: '게시됨', className: 'bg-green-100 text-green-700' },
};

function truncateContent(content: string, maxLength = 80): string {
  if (content.length <= maxLength) return content;
  return content.slice(0, maxLength) + '...';
}

export default function MeditationCard({ meditation }: MeditationCardProps) {
  const statusInfo = statusLabels[meditation.status] ?? {
    label: meditation.status,
    className: 'bg-gray-100 text-gray-700',
  };

  return (
    <Link href={`/meditation/${meditation.id}`}>
      <Card hoverable className="flex flex-col gap-sm">
        <div className="flex items-start justify-between gap-sm">
          <p className="flex-1 text-sm text-text-primary">{truncateContent(meditation.content)}</p>
          <div className="flex shrink-0 items-center gap-xs">
            {meditation.isAutoGenerated && (
              <span className="rounded-md bg-accent-light px-sm py-xs text-xs font-medium text-accent">
                AI
              </span>
            )}
            <span
              className={['rounded-md px-sm py-xs text-xs font-medium', statusInfo.className].join(
                ' ',
              )}
            >
              {statusInfo.label}
            </span>
          </div>
        </div>
        <p className="text-xs text-text-secondary">
          {new Date(meditation.createdAt).toLocaleDateString('ko-KR')}
        </p>
      </Card>
    </Link>
  );
}
