'use client';

import { useState } from 'react';
import Button from '@/components/ui/Button';
import Textarea from '@/components/ui/Textarea';

// FEAT-3: Meditation editor component

interface MeditationEditorProps {
  initialContent?: string;
  analysisId?: string;
  meditationId?: string;
  isAutoGenerated?: boolean;
  onSave: (content: string) => void;
  onCancel: () => void;
  onGenerate?: (analysisId: string) => Promise<string>;
  isSaving?: boolean;
}

export default function MeditationEditor({
  initialContent = '',
  analysisId,
  isAutoGenerated = false,
  onSave,
  onCancel,
  onGenerate,
  isSaving = false,
}: MeditationEditorProps) {
  const [content, setContent] = useState(initialContent);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showAiNotice, setShowAiNotice] = useState(isAutoGenerated);

  const handleGenerate = async () => {
    if (!analysisId || !onGenerate) return;

    setIsGenerating(true);
    const generated = await onGenerate(analysisId);
    setContent(generated);
    setShowAiNotice(true);
    setIsGenerating(false);
  };

  const handleSave = () => {
    if (content.trim().length === 0) return;
    onSave(content);
  };

  return (
    <div className="flex flex-col gap-md">
      {showAiNotice && (
        <div className="rounded-md bg-accent-light p-md text-sm text-accent">
          AI가 생성한 초안입니다. 자유롭게 수정하세요.
        </div>
      )}

      <Textarea
        label="묵상 내용"
        value={content}
        onChange={(e) => {
          setContent(e.target.value);
          if (showAiNotice && e.target.value !== content) {
            setShowAiNotice(false);
          }
        }}
        placeholder="말씀을 묵상하며 느낀 점을 자유롭게 적어보세요..."
        className="min-h-[200px]"
        disabled={isGenerating}
      />

      <div className="flex items-center justify-between">
        <div>
          {analysisId && onGenerate && (
            <Button
              variant="secondary"
              onClick={handleGenerate}
              loading={isGenerating}
              disabled={isSaving}
            >
              AI 자동 생성
            </Button>
          )}
        </div>
        <div className="flex items-center gap-sm">
          <Button variant="ghost" onClick={onCancel} disabled={isSaving || isGenerating}>
            취소
          </Button>
          <Button
            onClick={handleSave}
            loading={isSaving}
            disabled={content.trim().length === 0 || isGenerating}
          >
            저장
          </Button>
        </div>
      </div>
    </div>
  );
}
