import { http, HttpResponse } from 'msw';
import { mockMeditation, mockMeditationList } from '@/mocks/data/meditation';

// FEAT-3: Meditation API mock handlers
export const meditationHandlers = [
  // POST /api/v1/meditations - Create new meditation
  http.post('/api/v1/meditations', async () => {
    return HttpResponse.json(
      {
        data: {
          ...mockMeditation,
          id: 'meditation-new',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      },
      { status: 201 },
    );
  }),

  // GET /api/v1/meditations - List meditations with pagination
  http.get('/api/v1/meditations', async ({ request }) => {
    const url = new URL(request.url);
    const page = Number(url.searchParams.get('page') ?? '1');
    const limit = Number(url.searchParams.get('limit') ?? '10');

    return HttpResponse.json({
      data: mockMeditationList,
      meta: {
        page,
        limit,
        total: mockMeditationList.length,
        totalPages: Math.ceil(mockMeditationList.length / limit),
      },
    });
  }),

  // GET /api/v1/meditations/:id - Get meditation detail
  http.get('/api/v1/meditations/:id', async () => {
    return HttpResponse.json({
      data: mockMeditation,
    });
  }),

  // PUT /api/v1/meditations/:id - Update meditation
  http.put('/api/v1/meditations/:id', async ({ request }) => {
    const body = (await request.json()) as { content: string };
    return HttpResponse.json({
      data: {
        ...mockMeditation,
        content: body.content,
        updatedAt: new Date().toISOString(),
      },
    });
  }),

  // DELETE /api/v1/meditations/:id - Delete meditation
  http.delete('/api/v1/meditations/:id', async () => {
    return new HttpResponse(null, { status: 204 });
  }),

  // POST /api/v1/meditations/generate - Generate meditation from analysis
  http.post('/api/v1/meditations/generate', async () => {
    return HttpResponse.json({
      data: {
        id: 'meditation-generated',
        content:
          '이 구절에서 하나님의 사랑의 깊이를 묵상합니다. "이처럼"이라는 표현은 사랑의 정도가 측량할 수 없음을 나타냅니다. 독생자를 주셨다는 것은 가장 소중한 것을 내어주신 희생적 사랑을 의미합니다. 이 사랑은 조건 없이 "세상"을 향한 것이며, 믿는 자에게 영생이라는 선물을 약속합니다.',
        isAutoGenerated: true,
      },
    });
  }),
];
